[package]
name = "stratum-adapters"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
stratum-types.workspace = true
stratum-core.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true

[dev-dependencies]
rstest.workspace = true
stratum-test-utils.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
